# GitHub Actions for genCMPClient
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Siemens AG, 2021-2024

name: OpenSSL master

on: push

jobs:
  OpenSSL_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix kernel mmap rnd bits
      # Asan in llvm 14 provided in ubuntu 22.04 is incompatible with
      # high-entropy ASLR in much newer kernels that GitHub runners are
      # using leading to random crashes: https://reviews.llvm.org/D148280
        run: sudo sysctl vm.mmap_rnd_bits=28

      - name: set cache env
        run: |
         echo "cache-name=`git ls-remote https://github.com/openssl/openssl.git master | awk '{print $1}'`" >> "$GITHUB_ENV"
         echo "OPENSSL_DIR_INSTALL=`pwd`/master" >> $GITHUB_ENV

      - id: cache-openssl
        name: cache openssl
        uses: actions/cache@v3
        with:
          path: ${{ env.OPENSSL_DIR_INSTALL }}
          key: openssl-${{ env.cache-name }}-${{ runner.os }}-${{ runner.arch }}

      - if: ${{ steps.cache-openssl.outputs.cache-hit != 'true' }}
        name: build openssl
        run: |
          git clone https://github.com/openssl/openssl.git --branch master --depth 1
          cd openssl
          ./config --banner=Configured --strict-warnings --prefix=${{ env.OPENSSL_DIR_INSTALL }}  shared zlib
          make -s -j4
          sudo make install_sw install_ssldirs
          cd ..

      - name: set OpenSSL env
        run: |
          echo "OPENSSL_LIB=${{ env.OPENSSL_DIR }}/lib64" >> $GITHUB_ENV
          echo "${{ env.OPENSSL_DIR }}/bin" >> "$GITHUB_PATH"
          echo "LD_LIBRARY_PATH=${{ env.OPENSSL_DIR }}/lib64:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
      - name: Generate test certificate
        run: |
          cd test/recipes/80-test_cmp_http_data/Mock/
          ./setup-mock.sh all
          cd ../../../../
      - name: test Mock
        run: |
          which openssl
          make -f Makefile_v1 test_all V=1


