# GitHub Actions for genCMPClient
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Siemens AG, 2021-2025

name: Windows

on: push
jobs:
  cmake:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: cmake
        run: |
          mkdir build
          cd  build
          $env:GENCMP_NO_SECUTILS=1; cmake ..
          cmake --build . --config Release
  cmake-static:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: cmake-Static
        run: |
          mkdir build_static
          cd  build_static
          $env:GENCMP_NO_SECUTILS=1; cmake .. -DBUILD_STATIC_LIBS=ON
          cmake --build . --config Release
  cmake-debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name : cmake-Debug
        run: |
          mkdir build_debug
          cd  build_debug
          $env:GENCMP_NO_SECUTILS=1; cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --config Debug


