# GitHub Actions for genCMPClient
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Siemens AG, 2021-2025

name: Windows

on: push
jobs:
  cmake:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: cmake
        run: |
          cmake .
          echo "GENCMP_NO_TLS=1" >> $env:GITHUB_ENV
          echo "GENCMP_NO_SECUTILS=1" >> $env:GITHUB_ENV
          make; make clean

  Makefile_v1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Makefile_v1
        run: |
          GENCMP_NO_TLS=1 GENCMP_NO_SECUTILS=1 make -f Makefile_v1 clean build
